registry/paraswap/calldata-AugustusSwapper.json
addressAsEth  is referenced in the metadata and not in the display
=> fix the referrence in the august swapper json

.github/workflows/master.yml
- fix python setup
- do not require all valid descriptors to trigger CAL update
=> chore(BACK-7692): CI fixes

.github/workflows/pull_request.yml, .github/workflows/pull_request_setup.yml
to run from fork, labels action must be triggered with `pull_request_target` event, split workflow in 2 see https://github.com/actions/labeler#permissions
issue seen in #18
=> ci: fix labels action

specs/erc-7730.md, specs/erc7730-v1.schema.json
as discussed in https://ledger.slack.com/archives/C07KP6XKRBK/p1727343369568309?thread_ts=1726834924.685899&cid=C07KP6XKRBK
- address types are now an array
- address sources are no more an enum but free form
- fixed a small discrepancy between spec and schema, `nft` -> `collection`
\+ other unrelated typo fixes
=> chore: adapt schema for trusted names support

registry/uniswap/calldata-UniswapV3Router02.json
See https://github.com/LedgerHQ/ledger-asset-dapps/blob/211e75ed27de3894f592ca73710fa0b72c3ceeae/ethereum/uniswap/abis/0x68b3465833fb72a70ecdf485e0e4c7bd8665fc45.abi.json#L164-L199
Input field is `amountOutMinimum` (`amountOut` is the output)
=> fix: correct input field

specs/erc-7730.md, specs/erc7730-v1.schema.json
This allows validation to properly deal with omitted fields:
- field has no formatter and not in `excluded` => descriptor is invalid
- field has no formatter and is in `excluded` => OK, descriptor is valid
Example current linter output:
=> spec: add support for explicitly declaring excluded fields

.github/labeler.yml, .github/workflows/pull_request_setup.yml
To avoid failing the enforce labels workflow job for changes related to the preview tool
=> Add new label for preview-tool

developer-preview/src/app/ContractInfo.tsx
- Some contracts are deployed on multiple chains but have the same address on each
- We show a link to etherscan.io for each deployment address
- This meant we were showing lots of duplicates
-[x] Remove the duplicates
|Before|After|
|-|-|
|<img width="1511" alt="Screenshot 2024-10-15 at 14 20 31" src="https://github.com/user-attachments/assets/9669b475-e2b2-4e9b-b116-a9083ff9624e">|<img width="1512" alt="Screenshot 2024-10-15 at 14 20 46" src="https://github.com/user-attachments/assets/2804b9da-2609-4be8-b978-cfe6fc17804d">|
=> Remove duplicate address links

registry/paraswap/calldata-AugustusSwapper.json, registry/uniswap/calldata-UniswapV3Router02.json
- Fix incorrect fields in `registry/paraswap/calldata-AugustusSwapper.json`
- Fix path typo in `registry/paraswap/calldata-AugustusSwapper.json`
- Fix path typo in `registry/uniswap/calldata-UniswapV3Router02.json`
=> fix: typos

registry/lido/calldata-stETH.json, specs/erc-7730.md
fix "native currency value of the transaction" sometimes referred as `@.amount`, sometimes `@.value` => use `@.value` everywhere
=> fix: fix `@.amount`/`@.value` confusion

specs/erc7730-v1.schema.json
note: I did not enable arrays/objects (yet), as implementation of resolution is a bit more complex
=> spec: allow more data types in `$.metadata.constants` section

ercs/calldata-erc20-tokens.json, ercs/calldata-erc721-nfts.json, ercs/eip712-erc2612-permit.json, registry/aave/calldata-lpv2.json, registry/lido/calldata-OssifiableProxy.json, registry/lido/calldata-stETH.json, registry/lido/calldata-wstETH.json, registry/paraswap/calldata-AugustusSwapper.json, registry/poap/calldata-PoapBridge.json, registry/quickswap/calldata-QuickSwap.json, registry/uniswap/calldata-UniswapV3Router02.json, registry/uniswap/eip712-UniswapX-DutchOrder.json, registry/uniswap/eip712-UniswapX-ExclusiveDutchOrder.json, registry/uniswap/eip712-UniswapX-LimitOrder.json, registry/uniswap/eip712-uniswap-permit2.json
`types` and `sources` are mandatory for `addressName` format
(actual values I used probably needs some refinement)
Related: https://github.com/LedgerHQ/python-erc7730/pull/112
=> fix: add missing parameters for `addressName` formats

specs/erc-7730.md
went through jetbrains checks:
- fixed a few typos
- applied a few grammatical suggestions
- formatted tables
- fixed some invalid JSON examples
=> spec: typos/fixes

specs/erc7730-v1.schema.json
- `schemas` property can be `uri-reference | array[schema | uri-reference]`
- `uri-reference` can be a `<scheme>://` URL, or directly a relative (or absolute) path (`./foo` or `/foo`)
- Note that our implementation will allow `https` and `file` URL schemes, or relative paths. This is not enforced by schema/spec, not sure if it should
=> spec: add support for providing a single URL for all EIP-712 schemas

.github/workflows/master.yml
`LedgerHQ/crypto-assets-clear-signing-initiative` is now merged and archived
=> ci: remove trigger on archived repository

.github/workflows/format.yml
see https://github.com/LedgerHQ/python-erc7730/pull/147
job runs daily and opens a pull request with formatted descriptors
fixes #77
=> ci(BACK-7982): add workflow to format descriptors

registry/paraswap/calldata-AugustusSwapper-v5.json
This pr is linked to [this JIRA ticket](https://ledgerhq.atlassian.net/browse/BACK-8055)
Its resolution has shown off one error related to unused field declaration [here](https://github.com/LedgerHQ/python-erc7730/actions/runs/12034720106/job/33551951604?pr=154)
=> Remove unused field definition

specs/erc-7730.md
We need to be able to slice even primitive static types, as there are contracts encoding an address in a uint256 to add some metadata on remaining bytes.
That's the case for 1inch aggregation router v6.
The ethereum app on device already supports slices on static leafs.
=> Add support for slices applied on primitive static types

registry/starkgate/calldata-StarkGate-STRK.json
When testing on a device, I noticed 2 issues:
* Amount is displayed in ETH, and token in raw. Both should belong to the same tokenAmount field
* Those transactions have an ETH value, which should be clear signed as a deposit fee
=> Fix StarkGate descriptor

specs/erc-7730.md
EIP-712 `schemas` can be `url | array[schema | url]`
=> spec: update spec after #66

registry/uniswap/calldata-UniswapV3Router02.json
Slices end index is exclusive since that spec modification:
https://github.com/LedgerHQ/clear-signing-erc7730-registry/pull/83
It's also exclusive in SignerSDK and in the device, so that descriptor should be updated accordingly
=> fix: slices end index is exclusive

registry/1inch/calldata-AggregationRouterV3.json, registry/1inch/calldata-AggregationRouterV5.json, registry/1inch/common-AggregationRouterV4.json, registry/paraswap/calldata-AugustusSwapper.json
Display the last swap pool as a contract address, for selectors when we cannot know the destination token
=> feat: improve pool swap lisibility

registry/lombard/eip712-network-fee-authorization.json
- Adding the `chainId` and `verifyingContract` to the `domain` in hopes that this will make Clear Signing line up correctly
- Removing the extra holesky contract - this is the one that we want to use for now.
Example message:
(note, we will manually manipulate the `message.fee` to be an int instead of a string)
```
{
"domain": {
"name": "Lombard Staked Bitcoin",
"version": "1",
"chainId": 1,
"verifyingContract": "0x8236a87084f8B84306f72007F36F2618A5634494"
},
"message": {
"chainId": 1,
"fee": "523",
"expiry": 1740493350
},
"primaryType": "feeApproval",
"types": {
"EIP712Domain": [
{
"name": "name",
"type": "string"
},
{
"name": "version",
"type": "string"
},
{
"name": "chainId",
"type": "uint256"
},
{
"name": "verifyingContract",
"type": "address"
}
],
"feeApproval": [
{
"name": …
```
=> fix: [Lombard] adding the chainId and verifyingContract to the domain

registry/aave/calldata-lpv2.json, registry/aave/calldata-lpv3.json
Add Aave V2 and V3 pools for networks where Aave is deployed
Addresses can be found here: https://github.com/bgd-labs/aave-address-book it's maintained by BGD an Aave's service provider and it's directly used on multiple Aave's repo including [Aave frontend repo](https://github.com/aave/interface)
=> feat: add Aave pool addresses
